ignore_images: false

run_modules:
  - fastqc
  - samtools
  - preseq
  - deeptools
  - custom_content

module_order:
  - fastqc
  - samtools
  - preseq
  - deeptools
  - custom_content

custom_data:
  pct_duplicate:
    section_name: "Percent duplicate reads"
    file_format: "tsv"
    plot_type: "bargraph"
sp:
  pct_duplicate:
    fn: "*_pctDup.txt"
